### ISSUE TITLE
[gcc failed] non-dynamic relocations refer to dynamic symbol __libc_start_main

### ISSUE THREAD

**Issue by ImNotMyself** [ElonH/Rclone-OpenWrt#1]
Hello,

I got the errors below when building the Rclone by myself for Openwrt on MIPS(MT7621)
```shell
/usr/lib/go-1.13/pkg/tool/linux_mipsle/link: running gcc failed: exit status 1
/usr/bin/ld: non-dynamic relocations refer to dynamic symbol __libc_start_main
/usr/bin/ld: failed to set dynamic section sizes: Bad value
```
After searching around google,  I found the similar case you faced before and posted on  Openwrt forum [here](https://forum.openwrt.org/t/rclone-on-openwrt/10671/4) last month.

May I know your solution on how to tackle this error ? 
Thanks in advance!

**Comment by ElonH** [comment]
There are two situation.

1. If you really want to use OpenWrt SDK to build Rclone on MIPS, unfortunately, I still don't know how fix it.
2. If you just want to use Rclone on MIPS, only need to is that:

- download Rclone release version from official webpage.

- place executable to `/usr/bin` in router. 
  > The excutable of release version work fine. 
  > Advantages: It doesn't rely on other library. 
  > Disadvantages: It is big, whatever in memory or flash.

**Comment by ImNotMyself** [comment]
You may have a try to link it statically: 
https://github.com/golang/go/issues/26492#issuecomment-435462350

**Comment by ElonH** [comment]
Sorry for my delay. I was busy in other project in few day ago.
And sorry for my poor English.

I had fixed this problem. I tracked complie commands, and found that it is configuration error from golang package in openwrt package.

In [golang-package.mk:157](http://github.com/openwrt/packages/blob/master/lang/golang/golang-package.mk#L157), `CGO_ENABLED=1` should be set `CGO_ENABLED=0` or `CGO_DISABLED=1` (learn from [AdGraudHome](https://github.com/AdguardTeam/AdGuardHome/blob/master/release.sh#L13)).

`dev` branch not need to be modify, and you can compile rclone package without link error.
Only need to do is that modify flag `CGO_ENABLED` in golang-package.mk.

Note: The binary is little large (specifically 30M) , my MT7621 device has not enough space to run it. One idea is that using cifs mount network driver from other places.

I don't know if `CGO_ENABLED=1` is a bug in golang-package. Even that is not bug, but golang package didn't povide a option to enable/disable CGO.
