### ISSUE TITLE
已经在路由器中挂载，怎么通过局域网访问？

### ISSUE THREAD

**Issue by fyngd** [ElonH/Rclone-OpenWrt#10]
OpenWrt在挂载点中已经看到挂载的云盘，网络共享中也指到已挂载设备上的文件夹，但是却找不到共享的云盘文件夹。

**Comment by ElonH** [comment]
除非可以确认，使用官方rclone可以找到共享的云盘文件夹，但是本项目所生成的rclone二进制却不能找到共享文件夹，否则的话，这不是本项目的issue。

你应该去rclone那问问，可能是不支持该功能或者配置有问题
