### ISSUE TITLE
luci-app-rclone.postinst: /etc/init.d/rclone: not found

### ISSUE THREAD

**Issue by benathan** [ElonH/Rclone-OpenWrt#11]
prompted while installing/removing luci package

   //usr/lib/opkg/info/luci-app-rclone.postinst: line 273: /etc/init.d/rclone: not found
   //usr/lib/opkg/info/luci-app-rclone.postinst: line 275: /etc/init.d/rclone: not found

**Comment by ElonH** [comment]
Tested on
 - openwrt-19.07 (2df0ea042d)
 - arch: x86-64
