### ISSUE TITLE
无法在官方openwrt luci19.07后台启动.

### ISSUE THREAD

**Issue by garypang13** [ElonH/Rclone-OpenWrt#12]
官方openwrt master分支 luci19.07,无法在后台开启和关闭,只能通过命令rclone config --config /etc/rclone/rclone.conf开启

service rclone start
service rclone stop
service rclone restart
这些命令都无效. 都提示 -ash: /etc/init.d/rclone: not found,这个文件确定存在的,文件不存在的话会提示service "rclone" not found

**Comment by ElonH** [comment]
Tested on
 - openwrt-19.07 (2df0ea042d)
 - arch: x86-64
