### ISSUE TITLE
建议rclone-webui-react和rclone-ng设置为可选项而非强制依赖,

### ISSUE THREAD

**Issue by garypang13** [ElonH/Rclone-OpenWrt#15]
rclone-webui-react和rclone-ng 太大了,压缩包加起来都有10M,建议不要强制依赖,而是作为可选的子项.可以默认都选中,也给用户取消选中的选择,像我的话能用到的也就是rclone主程序.
https://github.com/ElonH/Rclone-OpenWrt/pull/16

**Comment by ElonH** [comment]
@garypang13 
luci 上面的按钮也需要做一些调整，
动态给出已安装 web 界面的按钮。

> 我记得luci-app-aria 有类似的功能，可以参考一下

**Comment by garypang13** [comment]
已增加动态调整web界面按钮.
