### ISSUE TITLE
Add this to official package feed?

### ISSUE THREAD

**Issue by thekiefs** [ElonH/Rclone-OpenWrt#19]
Hi are there any plans to add this to the official OpenWrt package feed so I can download directly from the webui?

**Comment by ElonH** [comment]
Hi, thank for your suggestion.

I confuse where is `the official rclone package feed`

**Comment by thekiefs** [comment]
Hi -- I clarified my response. I mean OpenWrt feed. Is there any plan to add it to the below?
https://github.com/openwrt/packages

Here are instructions:
https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

**Comment by ElonH** [comment]
Hi, @thekiefs 

Currently, I haven't plan to merge this  into Openwrt packages feeds. But I will submit codes to Openwrt when this project reach a certain stage.

---
This repo is a feed.

You can just add the below code into `feeds.conf` or `feeds.conf.default`

```
src-git Rclone https://github.com/ElonH/Rclone-OpenWrt.git
```

**Comment by lynxthecat** [comment]
@ElonH any chance you might add rclone to OpenWrt now? It's a really important package but not easy for users to build from scratch with build source for router. In any case please can you help with the below?

I have an RT3200 and am using a snapshot (OpenWrt SNAPSHOT r17471-b6cbbbb6ef). I am trying to create an rclone package for my router, but am strulling.

Can you or anyone advise as to the steps to build the rclone package?

I believe I need to download the source for hash : b6cbbbb6ef - how do do I do that?

I believe I need to amend feeds.conf to include the line:

`src-git Rclone https://github.com/ElonH/Rclone-OpenWrt.git`

Then what do I need to do to build the rclone package at that point?

I think this would be helpful for anyone else trying to get rclone to work in OpenWrt.

**Comment by ElonH** [comment]
@lynxthecat you can fork this repo, and you can modify it.
And if you can PR, I'm glad to see that.

**Comment by ElonH** [comment]
@lynxthecat 
Hi, you are using snapshot version, hash is useless.
You just need to download snapshot sdk to build rclone.
This is official documents.
https://openwrt.org/docs/guide-developer/using_the_sdk

**Comment by lynxthecat** [comment]
@ElonH thanks so much! It worked.
