### ISSUE TITLE
编译Error

### ISSUE THREAD

**Issue by MxCen** [ElonH/Rclone-OpenWrt#3]
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
can't load package: package github.com/rclone/rclone/.go_work/build: unknown import path "github.com/rclone/rclone/.go_work/build": cannot find module providing package github.com/rclone/rclone/.go_work/build

Cleaning module download cache (golang/go#27455)
go: finding github.com/rclone/rclone/.go_work/build latest
go: finding github.com/rclone/rclone/.go_work latest
can't load package: package github.com/rclone/rclone/.go_work/build: unknown import path "github.com/rclone/rclone/.go_work/build": cannot find module providing package github.com/rclone/rclone/.go_work/build

make[3]: *** [Makefile:77: /home/lede/lede/build_dir/target-x86_64_musl/rclone-1.50.2/.built] Error 1
make[3]: Leaving directory '/home/lede/openwrt-extra/Rclone-OpenWrt/rclone'
time: package/my-extra/Rclone-OpenWrt/rclone/compile#45.26#8.92#639.78
make[2]: *** [package/Makefile:109: package/my-extra/Rclone-OpenWrt/rclone/compile] Error 2
make[2]: Leaving directory '/home/lede/lede'
make[1]: *** [package/Makefile:103: /home/lede/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lede/lede'
make: *** [/home/lede/lede/include/toplevel.mk:218: world] Error 2

**Comment by ElonH** [comment]
这应该是网络的问题，确保开启全局代理，保持网络稳定和通畅。

**Comment by MxCen** [comment]
我在看看。开全局测试。谢谢！
