### ISSUE TITLE
编译安装后运行起来后无法使用。

### ISSUE THREAD

**Issue by MxCen** [ElonH/Rclone-OpenWrt#4]
lean大神的Openwrt固件，编译后，发现有点问题，主要表现为：

1、/etc/rclone文件夹中没有正确生成对应的配置文件rclone.conf，目录为空；
2、进入Luci后，显示绿色正在运行，但是点击Web管理界面后，输入Luci中的账号密码，提示：Error connecting. Please check username password and verify if rclone is working at the specified IP.
3、建议调整配置文件存储路径为：/var/etc/Rclone/rclone.conf

**Comment by MxCen** [comment]
更新：
进入Web管理界面，默认地址为http://192.168.1.1/rclone-webui-react/
修改为：http://192.168.1.1:5572后效验通过可以登录，建议优化解决下。

**Comment by ElonH** [comment]
@MxCen rclone 配置文件是记录 你的云账号名和token或密码。初始没添加账号就是空的目录。
个人建议在本机上运行 rclone ，添加自己的云存储账号， 然后再把本机上的 rclone 配置文件上传到路由器上面。
为什么需要把配置文件放到`/var/*`里？个人不是非常理解openwrt的结构，望指点。

**Comment by ElonH** [comment]
> 更新：
> 进入Web管理界面，默认地址为http://192.168.1.1/rclone-webui-react/
> 修改为：http://192.168.1.1:5572
> 输入账号密码后效验通过可以登录，建议优化解决下。

确实是一个不足的地方，目前正在尝试修改webui的代码，但是会可能会为了重新编译源码，不得不依赖 npm。
目前 webui 直接是下载打包好的 release 版本，所以不需要 npm。

一个临时方案是在 luci 上面写多一个提示

**Comment by MxCen** [comment]
第1个解答：
/etc的特点：包含了广泛的系统配置文件，这些配置文件几乎包含了系统配置的方方面面，是一个底层的重要项目，通常添加一些次等重要的零碎事物。
/var/etc的特点：包含系统运行时要改变的数据。其中包括每个系统是特定的，即不能够与其他计算机共享的目录。一般存储各类软件配置文件的都用这个目录。

第2个解答：
临时方案在 luci 上面写多一个提示，是比较好的，能够知道马上怎么用。
