### ISSUE TITLE
Insufficient permissions to read UCI configuration

### ISSUE THREAD

**Issue by benathan** [ElonH/Rclone-OpenWrt#6]
hello, I got the prompt below when I am installing luci-app-rclone

    //usr/lib/opkg/info/luci-app-rclone.postinst: line 273: /etc/init.d/rclone: not found
    //usr/lib/opkg/info/luci-app-rclone.postinst: line 275: /etc/init.d/rclone: not found

On the webpage it gives out the following error

    Insufficient permissions to read UCI configuration.

According to [https://forum.openwrt.org/t/insufficient-permissions-to-read-uci-configuration/61694/2](https://forum.openwrt.org/t/insufficient-permissions-to-read-uci-configuration/61694/2), the app need to be fixed to match the current LuCI ACL recuirements.

Any way to fix this error?

Thanks

**Comment by ElonH** [comment]
The issue of Insufficient permissions is fixed in https://github.com/ElonH/Rclone-OpenWrt/commit/3aab952a5c751aacb00a9197b8642ad5f34c7940 .

But I can't get any problem with `postinst` in installation.

**Comment by benathan** [comment]
Thanks, problem solved, Luci is running flawlessly. However I still  got the prompt when I am installing/removing rclone luci package, any workarounds? Do I supposed to open another issue?

**Comment by ElonH** [comment]
@benathan 
Sure, please create another issue.

I try to dig out the crux of the problem.

Thanks!
