### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Tomhitchman** [ElonH/Rclone-OpenWrt#7]
I clone the Git and try to compile using make and i receive error:

Makefile:34: /feeds/packages/lang/golang/golang-package.mk: No such file or directory
make: *** No rule to make target '/feeds/packages/lang/golang/golang-package.mk'.  Stop.

Im sure i have made a n00b mistake but any help is appreciated.
thanks

**Comment by ElonH** [comment]
The package `rclone` is dependent on the package `golang` for source compilation. 

Check official feeds [packages](https://github.com/openwrt/packages) if is installed properly.

Tip: https://github.com/openwrt/packages/tree/master/lang/golang
